import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export interface PostsInterface {
  slug: string;
}

export default function Home() {
  // Slug input
  const [slug, setSlug] = useState("");

  // Handle GoTo Button
  function handleGo() {
    window.location.href = "/posts/" + slug;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="main-section">
          <h1>Welcome to SSR Basics!</h1>
          <Link href={"/posts/Amit"}>Example Page (Amit)</Link>
          <div className="slug-form">
            <div>Enter your own slug</div>
            <input
              type="text"
              placeholder="slug"
              onChange={(e) => setSlug(e.target.value)}
              value={slug}
              className="slug-input"
            />
            <button type="button" onClick={handleGo}>
              Go To
            </button>
          </div>
        </section>
      </main>
    </>
  );
}
